"""
Plot utility for SelectionMechanismAnalyzer Excel outputs.

This script reads the Excel file generated by
`SelectionMechanismAnalyzer.export_to_excel(...)` and produces plots
without rerunning model training or feature selection.

Supported plot families:
- mean_curve: CV mean ± std curves from `curves_cv_all` (or custom sheet)
- delta_k: Δ-metric curves from `delta_<metric>_summary`
- sensitivity: perturbation curves from `noise_summary` or `down_summary`

Typical usage:
    python plot_from_selection_xlsx.py \
        --xlsx-path ../output_single_featimp/SelectionMechanismComp_entrance.xlsx \
        --plot-name mean_curve --metric rmse

Multiple plots in one run:
    python plot_from_selection_xlsx.py \
        --xlsx-path ../output_single_featimp/SelectionMechanismComp_entrance.xlsx \
        --plot-name mean_curve delta_k sensitivity
"""

import argparse
import os
from typing import Optional

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd


METHOD_COLORS = {
    "top_shap": "#FF8C00",
    "llm_selection": "#2CA02C",
    "fused_importance": "#1F77B4",
}


def normalize_method_name(method: str) -> str:
    if "llm_selection" in str(method):
        return "llm_selection"
    return str(method)


def get_method_color(method: str) -> str:
    return METHOD_COLORS.get(normalize_method_name(method), "#000000")


def infer_flow_type(xlsx_path: str) -> str:
    base = os.path.splitext(os.path.basename(xlsx_path))[0]
    prefix = "SelectionMechanismComp_"
    if base.startswith(prefix) and len(base) > len(prefix):
        return base[len(prefix):]
    return "flow"


def filter_target(df: pd.DataFrame, target: Optional[str]) -> pd.DataFrame:
    if target is None or "target" not in df.columns:
        return df
    return df[df["target"] == target].copy()


def plot_mean_curve_with_band_from_xlsx(
    curve_df: pd.DataFrame,
    flow_type: str,
    metric: str = "rmse",
    save_dir: Optional[str] = None,
    show: bool = True,
    target: Optional[str] = None,
):
    if metric not in ["rmse", "r2"]:
        raise ValueError("metric must be 'rmse' or 'r2'")

    curve_df = filter_target(curve_df, target)
    if curve_df.empty:
        raise ValueError("No rows found for the selected target.")

    targets = sorted(curve_df["target"].dropna().unique()) if "target" in curve_df.columns else ["target"]

    for t in targets:
        d0 = curve_df[curve_df["target"] == t].copy() if "target" in curve_df.columns else curve_df.copy()
        if d0.empty:
            continue

        agg = (
            d0.groupby(["method", "n_features"])
            .agg(mean=(metric, "mean"), std=(metric, "std"))
            .reset_index()
            .sort_values(["method", "n_features"])
        )

        plt.figure(figsize=(10, 6))
        for method in sorted(agg["method"].unique()):
            d = agg[agg["method"] == method].sort_values("n_features")
            x = d["n_features"].values
            y = d["mean"].values
            s = np.nan_to_num(d["std"].values, nan=0.0)

            label = normalize_method_name(method)
            color = get_method_color(method)

            plt.plot(x, y, marker="o", linewidth=2, label=label, color=color)
            plt.fill_between(x, y - s, y + s, alpha=0.20, color=color)

        plt.title(f"{flow_type} | {t} | CV Mean {metric} vs n_features")
        plt.xlabel("n_features")
        plt.ylabel(metric)
        plt.grid(True, alpha=0.3)
        plt.legend()
        plt.gca().xaxis.set_major_locator(mticker.MultipleLocator(1))
        plt.gca().xaxis.set_major_formatter(mticker.FormatStrFormatter("%d"))

        if save_dir:
            os.makedirs(save_dir, exist_ok=True)
            out_path = os.path.join(save_dir, f"{flow_type}_{t}_CVMean_{metric}.png")
            plt.tight_layout()
            plt.savefig(out_path, dpi=400)
            print(f"Saved: {out_path}")

        if show:
            plt.show()
        else:
            plt.close()


def plot_delta_k_with_band_from_xlsx(
    delta_summary_df: pd.DataFrame,
    flow_type: str,
    metric: str = "rmse",
    save_dir: Optional[str] = None,
    show: bool = True,
    target: Optional[str] = None,
):
    delta_summary_df = filter_target(delta_summary_df, target)
    if delta_summary_df.empty:
        raise ValueError("No rows found for the selected target.")

    targets = sorted(delta_summary_df["target"].dropna().unique()) if "target" in delta_summary_df.columns else ["target"]

    for t in targets:
        d0 = (
            delta_summary_df[delta_summary_df["target"] == t].copy()
            if "target" in delta_summary_df.columns
            else delta_summary_df.copy()
        )
        if d0.empty:
            continue

        plt.figure(figsize=(10, 6))

        for method in sorted(d0["method"].unique()):
            d = d0[d0["method"] == method].sort_values("n_features")
            x = d["n_features"].values
            y = d["delta_mean"].values
            s = np.nan_to_num(d["delta_std"].values, nan=0.0)

            label = normalize_method_name(method)
            color = get_method_color(method)

            plt.plot(x, y, marker="o", linewidth=2, label=label, color=color)
            plt.fill_between(x, y - s, y + s, alpha=0.20, color=color)

        plt.axhline(0, linewidth=1, alpha=0.6)
        plt.title(f"{flow_type} | {t} | Δ{metric} (CV mean±std) vs n_features")
        plt.xlabel("n_features (k)")
        plt.ylabel(f"Δ{metric} = {metric}(k) - {metric}(k-1)")
        plt.grid(True, alpha=0.3)
        plt.legend()
        plt.gca().xaxis.set_major_locator(mticker.MultipleLocator(1))
        plt.gca().xaxis.set_major_formatter(mticker.FormatStrFormatter("%d"))

        if save_dir:
            os.makedirs(save_dir, exist_ok=True)
            out_path = os.path.join(save_dir, f"{flow_type}_{t}_CVDelta_{metric}.png")
            plt.tight_layout()
            plt.savefig(out_path, dpi=400)
            print(f"Saved: {out_path}")

        if show:
            plt.show()
        else:
            plt.close()


def plot_sensitivity_mean_curves_from_xlsx(
    sens_summary_df: pd.DataFrame,
    flow_type: str,
    metric: str = "rmse",
    save_dir: Optional[str] = None,
    show: bool = True,
    max_panels: int = 6,
    target: Optional[str] = None,
):
    if metric not in ["rmse", "r2"]:
        raise ValueError("metric must be 'rmse' or 'r2'")

    sens_summary_df = filter_target(sens_summary_df, target)
    if sens_summary_df.empty:
        raise ValueError("No rows found for the selected target.")

    mean_col = f"{metric}_mean"
    std_col = f"{metric}_std"

    if mean_col not in sens_summary_df.columns or std_col not in sens_summary_df.columns:
        raise ValueError(f"Missing required columns: {mean_col} / {std_col}")

    perturb_type = sens_summary_df["perturb_type"].iloc[0] if "perturb_type" in sens_summary_df.columns else "perturb"
    vals = sorted(sens_summary_df["perturb_value"].unique())[:max_panels]

    targets = sorted(sens_summary_df["target"].dropna().unique()) if "target" in sens_summary_df.columns else ["target"]

    for t in targets:
        for pv in vals:
            d0 = sens_summary_df[(sens_summary_df["target"] == t) & (sens_summary_df["perturb_value"] == pv)].copy() if "target" in sens_summary_df.columns else sens_summary_df[sens_summary_df["perturb_value"] == pv].copy()
            if d0.empty:
                continue

            plt.figure(figsize=(10, 6))

            for method in sorted(d0["method"].unique()):
                d = d0[d0["method"] == method].sort_values("n_features")
                x = d["n_features"].values
                y = d[mean_col].values
                s = np.nan_to_num(d[std_col].values, nan=0.0)

                label = normalize_method_name(method)
                color = get_method_color(method)

                plt.plot(x, y, marker="o", linewidth=2, label=label, color=color)
                plt.fill_between(x, y - s, y + s, alpha=0.20, color=color)

            plt.title(f"{flow_type} | {t} | {metric} vs n_features | {perturb_type}={pv}")
            plt.xlabel("n_features")
            plt.ylabel(metric)
            plt.grid(True, alpha=0.3)
            plt.legend()

            if save_dir:
                os.makedirs(save_dir, exist_ok=True)
                out_path = os.path.join(save_dir, f"{flow_type}_{t}_{metric}_{perturb_type}_{pv}.png")
                plt.tight_layout()
                plt.savefig(out_path, dpi=400)
                print(f"Saved: {out_path}")

            if show:
                plt.show()
            else:
                plt.close()


def read_sheet(xlsx_path: str, sheet_name: str) -> pd.DataFrame:
    try:
        return pd.read_excel(xlsx_path, sheet_name=sheet_name)
    except ValueError as exc:
        xls = pd.ExcelFile(xlsx_path)
        raise ValueError(f"Sheet '{sheet_name}' not found. Available sheets: {xls.sheet_names}") from exc


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate SelectionMechanism comparison plots directly from exported Excel results "
            "(no retraining required)."
        )
    )
    parser.add_argument("--xlsx-path", required=True, help="Path to SelectionMechanismComp_*.xlsx")
    parser.add_argument(
        "--plot-name",
        required=True,
        nargs="+",
        choices=["mean_curve", "delta_k", "sensitivity"],
        help="One or more plot types to generate",
    )
    parser.add_argument("--metric", default="rmse", choices=["rmse", "r2"], help="Metric for plotting")
    parser.add_argument("--target", default=None, help="Optional single target filter, e.g., step_x")
    parser.add_argument("--flow-type", default=None, help="Optional flow type for title/file naming")
    parser.add_argument("--save-dir", default=None, help="Output directory for PNG files")
    parser.add_argument("--max-panels", type=int, default=6, help="Max perturbation panels for sensitivity plot")
    parser.add_argument(
        "--sensitivity-mode",
        default="noise",
        choices=["noise", "downsample"],
        help="Which sensitivity summary sheet to use",
    )
    parser.add_argument(
        "--delta-sheet",
        default=None,
        help="Optional explicit delta summary sheet name (overrides metric default)",
    )
    parser.add_argument(
        "--mean-sheet",
        default="curves_cv_all",
        help="Sheet for mean_curve plot. Usually curves_cv_all",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show matplotlib windows (omit for save-only mode)",
    )

    args = parser.parse_args()

    xlsx_path = args.xlsx_path
    if not os.path.exists(xlsx_path):
        raise FileNotFoundError(f"Excel file not found: {xlsx_path}")

    flow_type = args.flow_type if args.flow_type else infer_flow_type(xlsx_path)
    save_dir = args.save_dir if args.save_dir else os.path.dirname(xlsx_path)

    for plot_name in args.plot_name:
        if plot_name == "mean_curve":
            df = read_sheet(xlsx_path, args.mean_sheet)
            plot_mean_curve_with_band_from_xlsx(
                curve_df=df,
                flow_type=flow_type,
                metric=args.metric,
                save_dir=save_dir,
                show=args.show,
                target=args.target,
            )

        elif plot_name == "delta_k":
            default_delta_sheet = f"delta_{args.metric}_summary"
            delta_sheet = args.delta_sheet if args.delta_sheet else default_delta_sheet
            df = read_sheet(xlsx_path, delta_sheet)
            plot_delta_k_with_band_from_xlsx(
                delta_summary_df=df,
                flow_type=flow_type,
                metric=args.metric,
                save_dir=save_dir,
                show=args.show,
                target=args.target,
            )

        elif plot_name == "sensitivity":
            sens_sheet = "noise_summary" if args.sensitivity_mode == "noise" else "down_summary"
            df = read_sheet(xlsx_path, sens_sheet)
            plot_sensitivity_mean_curves_from_xlsx(
                sens_summary_df=df,
                flow_type=flow_type,
                metric=args.metric,
                save_dir=save_dir,
                show=args.show,
                max_panels=args.max_panels,
                target=args.target,
            )


if __name__ == "__main__":
    main()
